- name: github-action-tester
  # You may pin to the exact commit or the version.
  # uses: skx/github-action-tester@e29768ff4ff67be9d1fdbccd8836ab83233bebb1
  uses: skx/github-action-tester@release-0.10
  with:
    # The path to the test-script to run, within the repository.
    script: # optional, default is .github/run-tests.sh




# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. 
on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run o
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      - run: npm install

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: npm t

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
